name: Deploy_to_Github_Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 16.20.1
      uses: actions/setup-node@v2
      with:
        node-version: 16.20.1

    - name: Install dependencies and build
      run: |
        npm install
        CI=false npm run-script build
      env:
        REACT_APP_POLYGON_API_KEY: ${{ secrets.REACT_APP_POLYGON_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages
        FOLDER: build
